name: BUILD
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
			
      - name: Extract last 5 characters of GITHUB_SHA
        run: |
          SHA_SHORT=${GITHUB_SHA: -5}
          echo "RELEASE_VERSION=$SHA_SHORT" >> $GITHUB_ENV
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
			
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/codlab2:v${{ env.RELEASE_VERSION }} .
          

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/codlab2:v${{ env.RELEASE_VERSION }}
          

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.PEM_KEY }}" > carkey.pem
          chmod 600 carkey.pem
          
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i carkey.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          docker rm -f nginx || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/codlab2:v${{ env.RELEASE_VERSION }}
          docker run -d --name nginx -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/codlab2:v${{ env.RELEASE_VERSION }}
          EOF
